#!/usr/bin/env python3
"""shellvars.py — read plain NAME=value assignments out of a shell file.

The Python harness has to read three shell-syntax files that stay the source of
truth for the bash tests that remain:

    test/test_ports.sh      the central port registry (TEST_HARNESS_*_BASE)
    test/test_versions.sh   MOQT_TEST_VERSIONS, emitted into generated configs
    <build>/moqx-tools.env  MOQBIN, generated by CMake at configure time

Duplicating any of those into Python would let them drift, so they are parsed
instead. All three hold nothing but comments and literal assignments, which is
the only thing this understands: no expansion, no command substitution, no
line continuations. Anything else in the file is ignored rather than guessed at.

Usage:
    from lib.shellvars import read_shell_vars
    ports = read_shell_vars("test/test_ports.sh")
    base = int(ports["TEST_HARNESS_CHAIN_BASE"])
"""

from __future__ import annotations

import re
import shlex
from pathlib import Path

_ASSIGNMENT = re.compile(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$")


def read_shell_vars(path):
    """Return {name: value} for every literal assignment in a shell file.

    The right-hand side is lexed the way a shell would lex it, so one layer of
    matched quotes comes off and an unquoted trailing comment is dropped:

        MOQT_TEST_VERSIONS="[16]"          -> [16]
        MOQBIN='/some/path'  # generated   -> /some/path

    A '#' inside quotes stays data. Hand-rolling those two rules as separate
    branches gets the combination wrong — a quoted value followed by a comment
    is neither unquoted nor comment-free — which is why this defers to shlex.
    A value that does not lex (an unbalanced quote) is skipped rather than
    guessed at.
    """
    values = {}
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        match = _ASSIGNMENT.match(line)
        if not match:
            continue
        try:
            tokens = shlex.split(match.group(2), comments=True)
        except ValueError:
            continue
        values[match.group(1)] = " ".join(tokens)
    return values
