global:
  worker_threads: 4 # I/O threads; 0 = auto (num CPUs)
  log_level: info

  telemetry: ....

listeners:
  - name: main
    udp: # Exactly one of udp, tcp (maybe pipe, qmux?)
      socket:
        address: "::"
        port: 433
        ipv6_only: false
      transport:
        mvfst: # implementation specific config
          protocols:
            quic:
            webtransport:
          tunables:
            initial_congestion_control: bbr
            initial_rtt_ms: 100

    tls:
      # TODO: Tls credential providers
      # - Do we support more then one provider at a time?

  - name: tcp-fallback
    tcp:
      socket:
        address: "::"
        port: 443
      transport:
        proxygen: # I don't know who will implement webtransport/h2
    tls: ~ #TODO, see above

service_defaults:
  slow_subscriber_queue_max_bytes: 1000
  auth: {} #...
  cache: {} #...
  max_sessions: 50000

services:
  live-streaming:
    match:
      - authority: {exact: "live.example.com"}
        path: {exact: "/moq-relay"}
      - authority: {exact: "e79.x.akamaiedge.net"}
        path: {prefix: "/"}
      - authority: {exact: "1234567890.rsc.cdn77.org"}
        path: {prefix: "/"}

    # Tune batching e.g. Latency vs performance (aspirational)
    batching:
      min_batch_size: 100kib
      max_batch_delay: 250ms

    # By default all listeners, this can limit them (aspirational)
    listeners: ["main"]

    auth: #....

    provider:
      type: static_upstream
      config:
        upstream_uri: "moqt://origin.example.com:4433"

    cache: #....

    # TODO: How to handle per service-overrides?
    congestion_control: bbr

    tracks:
      # All tracks in given namespace prefix
      - namespace:
          prefix: ["live", "sports"]
        max_max_cache_duration_ms: 200
        slow_subscriber_queue_max: 500

      # I do thing that we need fairly advanced matching for examples MSF, where the catalog track may need different params. Is there a simplier way?
      - namespace:
          prefix:
            - exact: "live"
            - regex: "stream-[a-zA-Z0-9]+"
        track:
          exact: "catalog"
        batching:
          max_batch_delay: 50ms

  pure-relay:
    match:
      - authority: {wildcard: "*.moq-relay.example.com"}
        path: {prefix: "/"}
    auth_plugins:
      - anonymous

    provider:
      type: local-only

services_include:
  - /etc/moqx/services.d/*.yaml
